language: python
python:
- '3.5'
- '3.6'
install: pip install -r requirements.txt
after_success: zip -r latest.zip .
before_deploy:
- mkdir -p upload
- mv latest.zip upload/latest.zip
script: pytest

deploy:
  - provider: s3
    access_key_id:
      secure: KvRepiAN0CK/xHTZh3I27cLVJmVR0lWozUhZ7vD8Prc1CWCNG2etgIpYqyjDerC2CDci8Y2JzJb4Afi6msaSVyI5rcqS0z9fBOHhUB1lJtKKSuvmU20lWHWZ3PK36ZYMQr+iYM5+7ElAAR3OOomzLD7lIDBf/XcmwX05neDN1XA2VhZQLYNNsfzogGjAOqNqg7TVGYUtV3Dqcz4VspyUjoxdKiEJM5c0gwo3BwXl6Vy4LRyMx75qA8Yx+QuJUlKIkxn5xW8jhiSLlAKZ0YUA24Mpste/t0foKt1RBcLl3NeF2jM2d6xkYk7U9Co7brUse8n2W/NSjAj1LS+zKDZSwgh8KzmX5bQrcWxLlMDlDujJcqN16YnMNHi+PqfgVir0Hpo8/e4aB9Ig6lVdRLicQNvZPe3vjGLKEgiOp4FiWoQQaF+eMWbbXCSXVEYh61S1qFKCrRgagR6ti3Ozmkpck3sFdeeyIXImQaHRUAQvD0JNRGq4D49guVYaS6K7HUAkgueW9eHCI3uW2cZOIYcb2hQH3YHvOxvswf6MLO5KCj2Xbdr+HKQ370iiFns/TnxWh3bDQl6HvoMtaWAxeXN/BZAeD8r3WH6uikz7oLcUDPIdzvyDV8Tv7KeSfsWUpk+E4imWGQHLBGiOaDRliYEe53lfayUICiZie80ul1sZ9iA=
    secret_access_key:
      secure: mZLSwRHjSGO84DiM1hTWUa+NxoBvSuhwLi+CpR4n4Guf8LUk+I2J+vZmJpesT54MosUn3UicHq6lzY1wHHWEE0puIvCcPKArTH/HBhO2TFOZypDlqhJb3ZZi127S2Q3XetF6UTajTbZBdehMgCAFhH1NtKG1OJ158bLY+ZYRZ3B0EUf8ANAW2KefU5ltfYmevZuAM+Ndn2luUT/ubd9KOWbsm1kdwsGyZ8XDWRbHyFCBXesV+SDcYJmG5w9WH4WPGG9NIaXcAJiqzkJ2x4DoYX2CvCY6H+8QmczzDx36w15+US2TOyG1Zr8BF5Lrw4mZviB7RVZ3rrGA2yodGUF0LsuxOw9J1pr+xoagTs1y35hgyw2EP4u3VOrSZho8DOywf6o5yjPw/FkmDBFzjrJP1c5LerBELCvK7clejzcglpb4e0tNeMgEe+2WXtEoFSCdZl8gOkwO7Ht7jsuh9cMzAuJWKTeZ/I/pJ7sM11DX6BuneYVpW3SLGkJu4vOfJopptjOXACpsnyWA1rsnQDlns1WfWnnBVKOoCYcvHOKD5p0OHqKj2UOa0CbbFf+BhMvVDBo3NoFp/zypxymV/udEbZqQhzb1cudDadu3/cD84T0aLYNY+fhp55MMsIHzNFqPmsKRSw8GoVWaAxyLmteN3ZG3QsMsr/WlhD1lRulbfcs=
    local_dir: upload
    bucket: yosbot
    region: us-west-2
  - provider: codedeploy
    access_key_id:
      secure: KvRepiAN0CK/xHTZh3I27cLVJmVR0lWozUhZ7vD8Prc1CWCNG2etgIpYqyjDerC2CDci8Y2JzJb4Afi6msaSVyI5rcqS0z9fBOHhUB1lJtKKSuvmU20lWHWZ3PK36ZYMQr+iYM5+7ElAAR3OOomzLD7lIDBf/XcmwX05neDN1XA2VhZQLYNNsfzogGjAOqNqg7TVGYUtV3Dqcz4VspyUjoxdKiEJM5c0gwo3BwXl6Vy4LRyMx75qA8Yx+QuJUlKIkxn5xW8jhiSLlAKZ0YUA24Mpste/t0foKt1RBcLl3NeF2jM2d6xkYk7U9Co7brUse8n2W/NSjAj1LS+zKDZSwgh8KzmX5bQrcWxLlMDlDujJcqN16YnMNHi+PqfgVir0Hpo8/e4aB9Ig6lVdRLicQNvZPe3vjGLKEgiOp4FiWoQQaF+eMWbbXCSXVEYh61S1qFKCrRgagR6ti3Ozmkpck3sFdeeyIXImQaHRUAQvD0JNRGq4D49guVYaS6K7HUAkgueW9eHCI3uW2cZOIYcb2hQH3YHvOxvswf6MLO5KCj2Xbdr+HKQ370iiFns/TnxWh3bDQl6HvoMtaWAxeXN/BZAeD8r3WH6uikz7oLcUDPIdzvyDV8Tv7KeSfsWUpk+E4imWGQHLBGiOaDRliYEe53lfayUICiZie80ul1sZ9iA=
    secret_access_key:
      secure: mZLSwRHjSGO84DiM1hTWUa+NxoBvSuhwLi+CpR4n4Guf8LUk+I2J+vZmJpesT54MosUn3UicHq6lzY1wHHWEE0puIvCcPKArTH/HBhO2TFOZypDlqhJb3ZZi127S2Q3XetF6UTajTbZBdehMgCAFhH1NtKG1OJ158bLY+ZYRZ3B0EUf8ANAW2KefU5ltfYmevZuAM+Ndn2luUT/ubd9KOWbsm1kdwsGyZ8XDWRbHyFCBXesV+SDcYJmG5w9WH4WPGG9NIaXcAJiqzkJ2x4DoYX2CvCY6H+8QmczzDx36w15+US2TOyG1Zr8BF5Lrw4mZviB7RVZ3rrGA2yodGUF0LsuxOw9J1pr+xoagTs1y35hgyw2EP4u3VOrSZho8DOywf6o5yjPw/FkmDBFzjrJP1c5LerBELCvK7clejzcglpb4e0tNeMgEe+2WXtEoFSCdZl8gOkwO7Ht7jsuh9cMzAuJWKTeZ/I/pJ7sM11DX6BuneYVpW3SLGkJu4vOfJopptjOXACpsnyWA1rsnQDlns1WfWnnBVKOoCYcvHOKD5p0OHqKj2UOa0CbbFf+BhMvVDBo3NoFp/zypxymV/udEbZqQhzb1cudDadu3/cD84T0aLYNY+fhp55MMsIHzNFqPmsKRSw8GoVWaAxyLmteN3ZG3QsMsr/WlhD1lRulbfcs=
    region: us-west-2
    bucket: yosbot
    key: latest.zip
    bundle_type: zip
    application: yosbot
    deployment_group: yosbot-dg
    on:
      branch: master
      repo: colinwd/yosbot
    wait-until-deployed: true
